### ISSUE TITLE
Compilating error

### ISSUE THREAD

**Issue by vladobuwaba** [gentoo/gnome#9]
Hello to everybody. I have repeated error in emerge while compilating on my DeIl Inpiron.

**Comment by hartwork** [comment]
Hello @vladobuwaba,
please put more care into your next bug report. While the free software community welcomes bug reports in general, the quality of this report is so low that many would consider it offensive and disrespectful of developer time, to be 100% clear. If you Google for terms like "how to report bugs" you will find many useful articles about how to report bugs properly. Please take your time to get it right next time. Thanks for your cooperation!
